### ISSUE TITLE
CoD calculation for E1 and E2

### ISSUE THREAD

**Issue by tijeco** [Lexogen-Tools/SIRVsuite#3]
I see that this tool works with the equimolar E0, but is it possible to also use the E1 and E2 sets? In particular, I am interested in the CoD calculation for E1 and E2. I was wondering if there was some sort of mode that needs to be set in order to do that.

**Comment by TomasDrozd** [comment]
Dear Jeff,

thank you for reaching out. Unfortunately, at the moment the tool does not support the calculation of CoD for E1 and E2 SIRV mixes. However, we will take this into consideration for our further development.

Best regards,
Tomáš
